export const uiText = {
  common: {
    view: 'Xem',
    edit: 'Chỉnh sửa',
    save: 'Lưu',
    cancel: 'Hủy',
    delete: 'Xóa',
    create: 'Tạo',
    retry: 'Thử lại',
    loading: 'Đang tải...',
    loadingSubtitle: 'Vui lòng chờ trong khi dữ liệu được tải.',
    errorTitle: 'Đã xảy ra lỗi',
    emptyTitle: 'Chưa có dữ liệu',
    emptySubtitle: 'Hiện chưa có nội dung để hiển thị.',
    processing: 'Đang xử lý...',
    saveChanges: 'Lưu thay đổi',
    actions: 'Thao tác',
    confirmDelete: 'Bạn có chắc chắn muốn xóa?',
    product: 'Sản phẩm',
    note: 'Ghi chú',
  },
  navigation: {
    dashboard: 'Tổng quan',
    kpis: 'KPI',
    initiatives: 'Dự án trọng tâm',
    review: 'Rà soát tuần',
    alerts: 'Cảnh báo',
    notifications: 'Nhắc việc',
    digests: 'Bản tổng hợp',
    activity: 'Lịch sử thao tác',
    kpiProgress: 'Tiến độ KPI',
    logout: 'Đăng xuất',
  },
  status: {
    not_started: 'Chưa bắt đầu',
    in_progress: 'Đang thực hiện',
    blocked: 'Bị chặn',
    done: 'Hoàn thành',
  },
  severity: {
    critical: 'Nghiêm trọng',
    warning: 'Cảnh báo',
    healthy: 'Ổn',
    info: 'Thông tin'
  },
  kpiLabels: {
    target: 'Mục tiêu',
    targetToDate: 'Mục tiêu đến hiện tại',
    actual: 'Thực đạt',
    rawPercent: 'Tỷ lệ thực tế',
    normalizedPercent: 'Tỷ lệ quy đổi',
    score: 'Điểm',
    totalKpiScore: 'Điểm KPI',
    totalPersonScore: 'Tổng điểm nhân sự',
    subweight: 'Trọng số thành phần',
    month: 'Tháng',
    kpiScoreMethod: 'Cách tính điểm KPI',
    title: 'Tiêu đề',
    owner: 'Người phụ trách',
    type: 'Loại KPI',
    weight: 'Trọng số (%)',
    unit: 'Đơn vị tính',
    items: 'Hạng mục',
    description: 'Mô tả',
    manualProgress: 'Tiến độ thủ công',
    direction: 'Hướng (Cao/Thấp)',
    targetMode: 'Loại Mục tiêu',
  }
};
